info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
management:
  info:
    git:
      mode: "full"
server:
  error:
    include-message: always
    include-binding-errors: always